In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dt = pd.read_csv('USA_Housing.csv')

In [3]:
dt.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\r\nLaurabury, NE 37..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\r\nLake Kathleen, ..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\r\nDanieltown, WI 064..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\r\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\r\nFPO AE 09386

**This cell consist of an encoder importing which is used to conver categories from text to number. As we know that algorithm handles numerical data thats why it is used for that**

In [4]:
from sklearn.preprocessing import OrdinalEncoder

**In this cell we have call the ordinal function and afterwards we will fit our data in this model**

In [5]:
ordinal_encode = OrdinalEncoder()

In [6]:
df_encoded = ordinal_encode.fit_transform(dt)

In [7]:
df_encoded

array([[4253., 1942., 2512., ...,  468., 1563.,  962.],
       [4223., 2565., 1972., ..., 3274., 3890.,  863.],
       [1221., 2298., 4689., ..., 2642., 1562., 4069.],
       ...,
       [1581., 4506.,   87., ..., 1941., 1411., 1897.],
       [2363., 1644., 2758., ..., 3707., 2308., 4833.],
       [1923., 2539., 2083., ..., 4283., 2879., 1703.]], shape=(5000, 7))

In [8]:
ordinal_encode.categories_

[array([ 17796.63118954,  35454.71465948,  35608.98623708, ...,
        102881.12090227, 104702.72425703, 107701.74837764], shape=(5000,)),
 array([2.64430419, 2.6830429 , 2.79721495, ..., 9.00890009, 9.12528287,
        9.51908807], shape=(5000,)),
 array([ 3.23619402,  3.95022469,  3.95097265, ..., 10.21990198,
        10.28002242, 10.75958834], shape=(5000,)),
 array([2.  , 2.01, 2.02, 2.03, 2.04, 2.05, 2.06, 2.07, 2.08, 2.09, 2.1 ,
        2.11, 2.12, 2.13, 2.14, 2.15, 2.16, 2.17, 2.18, 2.19, 2.2 , 2.21,
        2.22, 2.23, 2.24, 2.25, 2.26, 2.27, 2.28, 2.29, 2.3 , 2.31, 2.32,
        2.33, 2.34, 2.35, 2.36, 2.37, 2.38, 2.39, 2.4 , 2.41, 2.42, 2.43,
        2.44, 2.45, 2.46, 2.47, 2.48, 2.49, 2.5 , 3.  , 3.01, 3.02, 3.03,
        3.04, 3.05, 3.06, 3.07, 3.08, 3.09, 3.1 , 3.11, 3.12, 3.13, 3.14,
        3.15, 3.16, 3.17, 3.18, 3.19, 3.2 , 3.21, 3.22, 3.23, 3.24, 3.25,
        3.26, 3.27, 3.28, 3.29, 3.3 , 3.31, 3.32, 3.33, 3.34, 3.35, 3.36,
        3.37, 3.38, 3.39, 3.4 , 3.41, 3.42, 3.43, 3.44, 3.45, 3.46, 3.47,
        3.48, 3.49, 3.5 , 4.  , 4.01, 4.02, 4.03, 4.04, 4.05, 4.06, 4.07,
        4.08, 4.09, 4.1 , 4.11, 4.12, 4.13, 4.14, 4.15, 4.16, 4.17, 4.18,
        4.19, 4.2 , 4.21, 4.22, 4.23, 4.24, 4.25, 4.26, 4.27, 4.28, 4.29,
        4.3 , 4.31, 4.32, 4.33, 4.34, 4.35, 4.36, 4.37, 4.38, 4.39, 4.4 ,
        4.41, 4.42, 4.43, 4.44, 4.45, 4.46, 4.47, 4.48, 4.49, 4.5 , 5.  ,
        5.01, 5.02, 5.03, 5.04, 5.05, 5.06, 5.07, 5.08, 5.09, 5.1 , 5.11,
        5.12, 5.13, 5.14, 5.15, 5.16, 5.17, 5.18, 5.19, 5.2 , 5.21, 5.22,
        5.23, 5.24, 5.25, 5.26, 5.27, 5.28, 5.29, 5.3 , 5.31, 5.32, 5.33,
        5.34, 5.35, 5.36, 5.37, 5.38, 5.39, 5.4 , 5.41, 5.42, 5.43, 5.44,
        5.45, 5.46, 5.47, 5.48, 5.49, 5.5 , 6.  , 6.01, 6.02, 6.03, 6.04,
        6.05, 6.06, 6.07, 6.08, 6.09, 6.1 , 6.11, 6.12, 6.13, 6.14, 6.15,
        6.16, 6.17, 6.18, 6.19, 6.2 , 6.21, 6.22, 6.23, 6.24, 6.25, 6.26,
        6.27, 6.28, 6.29, 6.3 , 6.31, 6.32, 6.33, 6.34, 6.35, 6.36, 6.37,
        6.38, 6.39, 6.4 , 6.41, 6.42, 6.43, 6.44, 6.45, 6.46, 6.47, 6.48,
        6.49, 6.5 ]),
 array([  172.61068627,  3285.45053752,  3883.44816401, ...,
        69575.44946366, 69592.04023599, 69621.71337779], shape=(5000,)),
 array([  15938.65792329,   31140.51762019,   88591.77016004, ...,
        2332110.74012441, 2370231.32010155, 2469065.5941747 ],
       shape=(5000,)),
 array(['000 Adkins Crescent\r\nSouth Teresa, AS 49642-1348',
        '000 Todd Pines\r\nAshleyberg, KY 90207-1179',
        '001 Steve Plaza\r\nJessicastad, UT 25190', ...,
        'Unit 9785 Box 0790\r\nDPO AP 60371-0797',
        'Unit 9831 Box 7128\r\nDPO AA 54705',
        'Unit 9871 Box 9037\r\nDPO AP 37275-9289'],
       shape=(5000,), dtype=object)]

In [9]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object
dtypes: float64(6), object(1)
memory usage: 273.6+ KB

In [10]:
to_encode = dt['Address']

In [11]:
to_encode

0       208 Michael Ferry Apt. 674\r\nLaurabury, NE 37...
1       188 Johnson Views Suite 079\r\nLake Kathleen, ...
2       9127 Elizabeth Stravenue\r\nDanieltown, WI 064...
3                             USS Barnett\r\nFPO AP 44820
4                            USNS Raymond\r\nFPO AE 09386
                              ...
4995                   USNS Williams\r\nFPO AP 30153-7653
4996              PSC 9258, Box 8489\r\nAPO AA 42991-3352
4997    4215 Tracy Garden Suite 076\r\nJoshualand, VA ...
4998                          USS Wallace\r\nFPO AE 73316
4999    37778 George Ridges Apt. 509\r\nEast Holly, NV...
Name: Address, Length: 5000, dtype: object

**one mthod is this and other is getting dumies from pandas**

In [12]:
pd.get_dummies(dt['Address'])

,"000 Adkins Crescent\r\nSouth Teresa, AS 49642-1348","000 Todd Pines\r\nAshleyberg, KY 90207-1179","001 Steve Plaza\r\nJessicastad, UT 25190","0010 Gregory Loaf\r\nSouth Ericfort, VA 34651-0718","00149 Raymond Knolls\r\nNew Jason, UT 75026","002 Katherine Flat\r\nHartmanland, AZ 37973-3049","0022 Young Rest\r\nLake Kevin, CA 25438-1821","0029 Melinda Neck Apt. 591\r\nLake Gregoryshire, HI 60267","003 Erica Passage Apt. 274\r\nEast Ritaton, KS 97261-8617","003 Fernando Gateway Suite 145\r\nEast Danielshire, GA 76041",...,Unit 9446 Box 0958\r\nDPO AE 97025,Unit 9463 Box 0963\r\nDPO AE 49984-2796,Unit 9494 Box 2307\r\nDPO AE 58622,Unit 9664 Box 1605\r\nDPO AA 30902,Unit 9732 Box 1846\r\nDPO AE 69898-3304,Unit 9774 Box 4511\r\nDPO AE 44963,Unit 9778 Box 2114\r\nDPO AP 59374,Unit 9785 Box 0790\r\nDPO AP 60371-0797,Unit 9831 Box 7128\r\nDPO AA 54705,Unit 9871 Box 9037\r\nDPO AP 37275-9289
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

<h1>Manually splitting test data</h1>

In [15]:
def split_train_test(data, test_ratio):
    shuffled_indices = np.random.permutation(len(dt))
    test_size = int(len(dt) * test_ratio)
    test_indices = shuffled_indices[:test_size]
    train_indices = shuffled_indices[test_size:]
    np.random.seed(42)
    return dt.iloc[train_indices], dt.iloc[test_indices]

In [16]:
train_set, test_set = split_train_test(dt, 0.2)

In [18]:
len(train_set)

4000

In [19]:
len(test_set)

1000